import type { KeywordRecord } from "@/lib/types";

export const SEED_KEYWORDS: Omit<KeywordRecord, "id">[] = [
  {
    keyword: "septic tank installation tucson",
    intent: "transactional",
    service: "septic-installation",
    city: "tucson",
    priority: "high",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "GSC top query Aug 2026",
    landingPage: "/az/tucson/septic-installation",
  },
  {
    keyword: "septic system installation tucson",
    intent: "transactional",
    service: "septic-installation",
    city: "tucson",
    priority: "high",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "GSC top query Aug 2026",
    landingPage: "/az/tucson/septic-installation",
  },
  {
    keyword: "septic tucson",
    intent: "commercial",
    service: "",
    city: "tucson",
    priority: "high",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "GSC hub query",
    landingPage: "/az/tucson",
  },
  {
    keyword: "septic service tucson az",
    intent: "commercial",
    service: "",
    city: "tucson",
    priority: "high",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "GSC hub query",
    landingPage: "/az/tucson",
  },
  {
    keyword: "tucson septic service",
    intent: "commercial",
    service: "",
    city: "tucson",
    priority: "high",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "GSC hub query",
    landingPage: "/az/tucson",
  },
  {
    keyword: "emergency septic repair near me",
    intent: "transactional",
    service: "emergency-septic-service",
    city: "",
    priority: "high",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "GSC — target local emergency pages, not /near-me URL",
    landingPage: "/emergency-septic-service",
  },
  {
    keyword: "emergency septic pumping near me",
    intent: "transactional",
    service: "emergency-septic-service",
    city: "",
    priority: "high",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "GSC — target local emergency pages",
    landingPage: "/az/tucson/emergency-septic-service",
  },
  {
    keyword: "septic system cleaning near me",
    intent: "transactional",
    service: "septic-tank-cleaning",
    city: "",
    priority: "high",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "GSC top query Aug 2026",
    landingPage: "/septic-tank-cleaning",
  },
  {
    keyword: "septic tank and drain field repair",
    intent: "transactional",
    service: "drain-field-repair",
    city: "",
    priority: "high",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "GSC top query Aug 2026",
    landingPage: "/drain-field-repair",
  },
  {
    keyword: "septic pumping tucson",
    intent: "transactional",
    service: "septic-pumping",
    city: "tucson",
    priority: "high",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "Launch cluster primary",
    landingPage: "/az/tucson/septic-pumping",
  },
  {
    keyword: "septic repair tucson",
    intent: "commercial",
    service: "septic-repair",
    city: "tucson",
    priority: "high",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "High lead value even at lower volume",
    landingPage: "/az/tucson/septic-repair",
  },
  {
    keyword: "septic tank pumping cost",
    intent: "commercial",
    service: "septic-pumping",
    city: "",
    priority: "medium",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "Guide with quote funnel",
    landingPage: "/septic-tank-pumping-cost",
  },
  {
    keyword: "how often pump septic tank",
    intent: "informational",
    service: "septic-pumping",
    city: "",
    priority: "medium",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "Informational / soft CTA",
    landingPage: "/signs-septic-tank-is-full",
  },
  {
    keyword: "septic inspection tucson",
    intent: "commercial",
    service: "septic-inspection",
    city: "tucson",
    priority: "medium",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "Existing city page",
    landingPage: "/az/tucson/septic-inspection",
  },
];
