import type { KeywordRecord } from "@/lib/types";

export const SEED_KEYWORDS: Omit<KeywordRecord, "id">[] = [
  {
    keyword: "septic pumping tucson",
    intent: "transactional",
    service: "septic-pumping",
    city: "tucson",
    priority: "high",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "Launch cluster primary",
    landingPage: "/az/tucson/septic-pumping",
  },
  {
    keyword: "septic tank pumping tucson",
    intent: "transactional",
    service: "septic-pumping",
    city: "tucson",
    priority: "high",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "Strong commercial intent",
    landingPage: "/az/tucson/septic-pumping",
  },
  {
    keyword: "septic repair tucson",
    intent: "commercial",
    service: "septic-repair",
    city: "tucson",
    priority: "high",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "High lead value even at lower volume",
    landingPage: "/az/tucson/septic-repair",
  },
  {
    keyword: "emergency septic service",
    intent: "transactional",
    service: "emergency-septic-service",
    city: "",
    priority: "high",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "Urgency cluster",
    landingPage: "/emergency-septic-service",
  },
  {
    keyword: "septic tank pumping cost",
    intent: "commercial",
    service: "septic-pumping",
    city: "",
    priority: "medium",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "Guide with quote funnel",
    landingPage: "/septic-tank-pumping-cost",
  },
  {
    keyword: "how often pump septic tank",
    intent: "informational",
    service: "septic-pumping",
    city: "",
    priority: "medium",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "Informational / soft CTA",
    landingPage: "/signs-septic-tank-is-full",
  },
  {
    keyword: "drain field repair near me",
    intent: "transactional",
    service: "drain-field-repair",
    city: "",
    priority: "high",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "Target via /az/tucson/drain-field-repair, not near-me URL",
    landingPage: "/az/tucson/drain-field-repair",
  },
  {
    keyword: "septic inspection tucson",
    intent: "commercial",
    service: "septic-inspection",
    city: "tucson",
    priority: "medium",
    impressions: 0,
    clicks: 0,
    ctr: 0,
    position: 0,
    leads: 0,
    estimatedValue: 0,
    notes: "Create page / improve existing",
    landingPage: "/az/tucson/septic-inspection",
  },
];
