export type ProviderProspect = {
  companyName: string;
  phone: string;
  email?: string;
  website?: string;
  city: string;
  state: string;
  zip?: string;
  serviceAreaCities: string[];
  servicesOffered: string[];
  emergencyService?: boolean;
  sourceLabel: string;
  sourceUrl: string;
  notes?: string;
};

const FULL_SERVICE = [
  "septic-pumping",
  "septic-repair",
  "septic-inspection",
  "emergency-septic-service",
];

export const PROVIDER_PROSPECTS: ProviderProspect[] = [
  {
    companyName: "Fearless Contracting Inc. Septic Service",
    phone: "520-200-3327",
    city: "Tucson",
    state: "AZ",
    zip: "85706",
    serviceAreaCities: ["Tucson", "Marana", "Sahuarita", "Vail", "Oro Valley", "Catalina"],
    servicesOffered: [...FULL_SERVICE, "septic-installation"],
    sourceLabel: "Local business listing",
    sourceUrl: "https://www.google.com/search?q=Fearless+Contracting+Inc+Septic+Service+Tucson",
    notes: "Priority Tucson prospect. Strong local septic focus with pumping, inspections, repairs and installs.",
  },
  {
    companyName: "Reliable Septic Service, Inc.",
    phone: "520-800-8050",
    city: "Tucson",
    state: "AZ",
    zip: "85756",
    serviceAreaCities: ["Tucson", "Marana", "Sahuarita", "Vail", "Oro Valley"],
    servicesOffered: [...FULL_SERVICE, "septic-installation"],
    emergencyService: true,
    sourceLabel: "Local business listing",
    sourceUrl: "https://www.google.com/search?q=Reliable+Septic+Service+Tucson",
    notes: "Priority Tucson prospect. Residential septic pumping, inspections, repairs and new system work.",
  },
  {
    companyName: "Gross Septic Pumping",
    phone: "520-742-1369",
    city: "Tucson",
    state: "AZ",
    zip: "85704",
    serviceAreaCities: ["Tucson", "Marana", "Vail", "Sahuarita", "Catalina", "Picture Rocks", "Avra Valley"],
    servicesOffered: ["septic-pumping", "septic-repair", "septic-inspection"],
    sourceLabel: "Local business listing",
    sourceUrl: "https://www.google.com/search?q=Gross+Septic+Pumping+Tucson",
    notes: "Priority Tucson prospect with strong pumping/maintenance fit.",
  },
  {
    companyName: "Old Pueblo Septic & Drain Service",
    phone: "520-744-1100",
    city: "Tucson",
    state: "AZ",
    zip: "85741",
    serviceAreaCities: ["Tucson", "Marana", "Catalina", "Vail"],
    servicesOffered: ["septic-pumping", "septic-repair", "septic-inspection", "emergency-septic-service"],
    emergencyService: true,
    sourceLabel: "Local business listing / Arizona State procurement",
    sourceUrl: "https://www.google.com/search?q=Old+Pueblo+Septic+Drain+Service+Tucson",
    notes: "Long-running Tucson septic company; pumping, certifications and emergency response.",
  },
  {
    companyName: "Quality Septic",
    phone: "480-243-1515",
    city: "Phoenix",
    state: "AZ",
    zip: "85029",
    serviceAreaCities: ["Phoenix", "Glendale", "Peoria", "Scottsdale", "Buckeye", "New River", "Rio Verde"],
    servicesOffered: ["septic-pumping", "septic-inspection"],
    sourceLabel: "Local business listing / BBB",
    sourceUrl: "https://www.google.com/search?q=Quality+Septic+Phoenix+AZ",
    notes: "Phoenix prospect focused on septic pumping and inspections.",
  },
  {
    companyName: "A-American Septic Service",
    phone: "602-462-5858",
    city: "Phoenix",
    state: "AZ",
    zip: "85034",
    serviceAreaCities: ["Phoenix", "Scottsdale", "Glendale", "Tempe", "Mesa"],
    servicesOffered: [...FULL_SERVICE, "septic-installation"],
    sourceLabel: "Local business listing",
    sourceUrl: "https://www.google.com/search?q=A-American+Septic+Service+Phoenix",
    notes: "Full-service Phoenix prospect covering pumping, repair, design and installation.",
  },
  {
    companyName: "Sewer Time Septic & Drain",
    phone: "480-900-8820",
    website: "https://sewertime.com/",
    city: "Phoenix",
    state: "AZ",
    serviceAreaCities: ["Phoenix", "Scottsdale", "Cave Creek", "Mesa", "Gilbert", "Glendale", "Peoria", "Tempe"],
    servicesOffered: [...FULL_SERVICE, "septic-installation"],
    emergencyService: true,
    sourceLabel: "Company website",
    sourceUrl: "https://sewertime.com/",
    notes: "Phoenix metro full-service septic prospect; advertises same-day/emergency response.",
  },
  {
    companyName: "Macho Contracting",
    phone: "602-730-7715",
    city: "Phoenix",
    state: "AZ",
    zip: "85024",
    serviceAreaCities: ["Phoenix", "Mesa", "Cave Creek", "Carefree", "Paradise Valley", "New River", "Fountain Hills"],
    servicesOffered: ["septic-pumping", "septic-repair", "septic-inspection", "septic-installation"],
    sourceLabel: "Local business listing",
    sourceUrl: "https://www.google.com/search?q=Macho+Contracting+Phoenix+septic",
    notes: "Phoenix/North Valley plumbing and septic prospect.",
  },
  {
    companyName: "RVC Pumping & Septic",
    phone: "916-250-9726",
    city: "Sacramento",
    state: "CA",
    serviceAreaCities: ["Sacramento", "Roseville", "Rocklin", "Penryn", "Auburn"],
    servicesOffered: ["septic-pumping", "septic-repair", "emergency-septic-service"],
    emergencyService: true,
    sourceLabel: "Local business listing",
    sourceUrl: "https://www.google.com/search?q=RVC+Pumping+Septic+Sacramento",
    notes: "Greater Sacramento pumping and wastewater prospect.",
  },
  {
    companyName: "A-1 Septic & Backhoe Service",
    phone: "916-371-4160",
    email: "A1SEPTIC@YAHOO.COM",
    city: "West Sacramento",
    state: "CA",
    zip: "95691",
    serviceAreaCities: ["Sacramento", "West Sacramento", "Davis", "Woodland"],
    servicesOffered: ["septic-pumping", "septic-repair", "septic-installation"],
    sourceLabel: "Sacramento County contractor list",
    sourceUrl: "https://emd.saccounty.gov/EC/Documents/Liquid%20Waste/Septic%20Contractor%20List%20rev%205-21-25.pdf",
    notes: "Listed by Sacramento County on its septic system contractor list; verify current license/contact before outreach.",
  },
  {
    companyName: "Central Valley Septic",
    phone: "209-369-5027",
    city: "Lodi",
    state: "CA",
    zip: "95242",
    serviceAreaCities: ["Sacramento", "Lodi", "Galt", "Elk Grove"],
    servicesOffered: ["septic-pumping", "septic-repair", "septic-installation"],
    sourceLabel: "Sacramento County contractor list",
    sourceUrl: "https://emd.saccounty.gov/EC/Documents/Liquid%20Waste/Septic%20Contractor%20List%20rev%205-21-25.pdf",
    notes: "Regional prospect appearing on Sacramento County contractor list; verify service radius before outreach.",
  },
  {
    companyName: "TCS Septic Pumping",
    phone: "719-492-6818",
    city: "Colorado Springs",
    state: "CO",
    zip: "80906",
    serviceAreaCities: ["Colorado Springs", "Fountain", "Security-Widefield", "Monument"],
    servicesOffered: ["septic-pumping"],
    sourceLabel: "El Paso County Public Health licensed cleaners",
    sourceUrl: "https://www.elpasocountyhealth.org/licenses-permits-inspections-water-testing/onsite-wastewater-treatment-systems/licensed-cleaners/",
    notes: "Licensed system cleaner listed by El Paso County Public Health.",
  },
  {
    companyName: "PF McCarthy Inc",
    phone: "719-260-1354",
    city: "Colorado Springs",
    state: "CO",
    zip: "80907",
    serviceAreaCities: ["Colorado Springs", "Fountain", "Monument"],
    servicesOffered: ["septic-pumping"],
    sourceLabel: "El Paso County Public Health licensed cleaners",
    sourceUrl: "https://www.elpasocountyhealth.org/licenses-permits-inspections-water-testing/onsite-wastewater-treatment-systems/licensed-cleaners/",
    notes: "Licensed system cleaner listed by El Paso County Public Health.",
  },
  {
    companyName: "A1 Septic Services",
    phone: "719-399-3365",
    city: "Colorado Springs",
    state: "CO",
    zip: "80920",
    serviceAreaCities: ["Colorado Springs", "Fountain", "Monument"],
    servicesOffered: ["septic-pumping"],
    sourceLabel: "El Paso County Public Health licensed cleaners",
    sourceUrl: "https://www.elpasocountyhealth.org/licenses-permits-inspections-water-testing/onsite-wastewater-treatment-systems/licensed-cleaners/",
    notes: "Licensed system cleaner listed by El Paso County Public Health.",
  },
  {
    companyName: "Advanced Septic Solutions",
    phone: "719-628-5611",
    city: "Colorado Springs",
    state: "CO",
    serviceAreaCities: ["Colorado Springs", "Fountain", "Monument", "El Paso County"],
    servicesOffered: ["septic-repair", "septic-installation", "septic-inspection"],
    sourceLabel: "Local business listing",
    sourceUrl: "https://www.google.com/search?q=Advanced+Septic+Solutions+Colorado+Springs",
    notes: "Colorado Springs septic/excavation prospect focused on installation and repair work.",
  },
];
